---
abstract: 'install chromedriver'
author:
  - 'Hiroki Honda (Cside) <cside.story(at)gmail.com>'
build_requires:
  File::ShareDir: 0
configure_requires:
  LWP::Simple: 0
  Module::Build: 0
  Web::Query: 0
  autodie: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-ChromeDriver
no_index:
  directory:
    - inc
    - author
provides:
  Alien::ChromeDriver:
    file: lib/Alien/ChromeDriver.pm
    version: 0.01
requires:
  File::ShareDir: 1.00
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
